Repository ikarus-project/ikarus, pull requests merged in 2022-11, with the labels that each got.

#84 Update README.md
  README.md
Labels: bug

#107 Add workflow to check, if examples are still working
  .github/workflows/runExamples.yml
Labels: enhancement

#106 added documentation for IkarusExamples
  docs/literature.bib
  docs/mkdocs.yml
  docs/website/examples.md
  docs/website/examples/integrate_pi.md
Labels: documentation
