Repository ikarus-project/ikarus, pull requests merged in 2024-07, with the labels that each got.

#304 Add AssemblerManipulator to manipulate the assembled quantities
  CHANGELOG.md
  ikarus/assembler/CMakeLists.txt
  ikarus/assembler/assemblermanipulatorbuildingblocks.hh
  ikarus/assembler/assemblermanipulatorfuser.hh
  ikarus/assembler/interface.hh
  ikarus/assembler/simpleassemblers.hh
  ikarus/assembler/simpleassemblers.inl
  ikarus/python/assembler/CMakeLists.txt
  ikarus/python/assembler/flatassembler.hh
  ikarus/python/assembler/flatassemblermanipulator.hh
  ikarus/python/finiteelements/CMakeLists.txt
  ikarus/python/finiteelements/registerferequirements.hh
  ikarus/python/finiteelements/scalarwrapper.hh
  ikarus/python/finiteelements/valuewrapper.hh
  ikarus/python/test/debug_info.py
  ikarus/python/test/kltest.py
  ikarus/python/test/linearelastictest.py
  ikarus/python/test/nonlinearelastictest.py
  ikarus/utils/concepts.hh
  ikarus/utils/dirichletvalues.hh
  ikarus/utils/functionhelper.hh
  ikarus/utils/traits.hh
  ikarus/utils/traversal.hh
  python/ikarus/__init__.py
  python/ikarus/_ikarus.cc
  python/ikarus/assembler/__init__.py
  python/ikarus/utils/__init__.py
  tests/src/testassembler.cpp
  tests/src/testdirichletvalue.cpp
  tests/src/testfeelement.hh
Labels: enhancement, feature

#310 fix PR links in the CHANGELOG
  CHANGELOG.md
Labels: bug

#305 Homogenize Python Bindings for DirichletValues + Support for fixing Subspace Basis
  CHANGELOG.md
  docs/website/01_framework/dirichletBCs.md
  ikarus/python/dirichletvalues/dirichletvalues.hh
  ikarus/python/finiteelements/fe.hh
  ikarus/python/finiteelements/registerferequirements.hh
  ikarus/python/test/CMakeLists.txt
  ikarus/python/test/dirichletvaluetest.py
  ikarus/python/test/kltest.py
  ikarus/python/test/linearelastictest.py
  ikarus/python/test/nonlinearelastictest.py
  ikarus/python/test/testmaterials.py
  ikarus/utils/dirichletvalues.hh
  python/ikarus/dirichlet_values.py
  tests/src/testassembler.cpp
  tests/src/testdirichletvalue.cpp
Labels: feature, fix

#311 Hotfix: Size property of assembler & assemblermanipulator
  .gitignore
  CHANGELOG.md
  ikarus/assembler/assemblermanipulatorfuser.hh
  ikarus/python/assembler/flatassembler.hh
  ikarus/python/test/linearelastictest.py
  ikarus/utils/functionhelper.hh
  ikarus/utils/nonlinopfactory.hh
  python/ikarus/assembler/__init__.py
  tests/src/testassembler.cpp
Labels: fix, python

#302 Add a truss element
  .github/workflows/style.yml
  .reuse/dep5
  CHANGELOG.md
  ikarus/finiteelements/feresulttypes.hh
  ikarus/finiteelements/mechanics/CMakeLists.txt
  ikarus/finiteelements/mechanics/truss.hh
  ikarus/python/finiteelements/registerpreelement.hh
  ikarus/python/test/CMakeLists.txt
  ikarus/python/test/auxiliaryfiles/truss2d.msh
  ikarus/python/test/auxiliaryfiles/truss3d.msh
  ikarus/python/test/trusstest.py
  ikarus/utils/nonlinearoperator.hh
  python/ikarus/finite_elements/__init__.py
  sandbox/src/auxiliaryFiles/circle.msh
  tests/src/CMakeLists.txt
  tests/src/checkfebyautodiff.hh
  tests/src/testcommon.hh
  tests/src/testhelpers.hh
  tests/src/testtruss.cpp
Labels: feature

#291 Add an About Ikarus page in the documentation
  CHANGELOG.md
  docs/mkdocs.yml
  docs/website/about.md
  docs/website/index.md
Labels: documentation

#313 add .clangd
  .clangd
Labels: enhancement

#312 Rework `canProvideResultType()`
  ikarus/finiteelements/feresulttypes.hh
  ikarus/finiteelements/mechanics/enhancedassumedstrains.hh
  ikarus/finiteelements/mechanics/kirchhoffloveshell.hh
  ikarus/finiteelements/mechanics/linearelastic.hh
  ikarus/finiteelements/mechanics/nonlinearelastic.hh
  ikarus/finiteelements/mechanics/truss.hh
  tests/src/testfeelement.hh
Labels: enhancement
