Repository ikarus-project/ikarus, pull requests merged in 2024-01, with the labels that each got.

#218 fixes in documentation for examples - iks003, iks004, and iks007
  docs/website/02_examples/incompressibleRubberBlock.md
  docs/website/02_examples/kirchhoffPlate.md
  docs/website/02_examples/vonMisesTruss.md
Labels: documentation

#226 Update .clang-format
  .clang-format
  ikarus/finiteelements/mechanics/materials/interface.hh
  ikarus/finiteelements/mechanics/materials/vanishingstress.hh
  ikarus/io/resultevaluators.hh
  ikarus/utils/autodiffhelper.hh
  ikarus/utils/pythonautodiffdefinitions.hh
  tests/src/testmanifolds.cpp
Labels: bug

#230 rename FErequirements to FERequirements
  docs/website/01_framework/finiteElements.md
  docs/website/02_examples/incompressibleRubberBlock.md
  ikarus/controlroutines/pathfollowing.hh
  ikarus/finiteelements/febases/autodifffe.hh
  ikarus/finiteelements/ferequirements.hh
  ikarus/finiteelements/mechanics/kirchhoffloveshell.hh
  ikarus/finiteelements/mechanics/linearelastic.hh
  ikarus/finiteelements/mechanics/nonlinearelastic.hh
  ikarus/python/finiteelements/kirchhoffloveshell.hh
  ikarus/python/finiteelements/nonlinearelastic.hh
  ikarus/python/finiteelements/registerelement.hh
  ikarus/python/test/kltest.py
  ikarus/python/test/linearelastictest.py
  ikarus/python/test/nonlinearelastictest.py
  python/ikarus/_ikarus.cc
  python/ikarus/finite_elements/__init__.py
  tests/src/testadaptivestepsizing.cpp
  tests/src/testassembler.cpp
  tests/src/testeas.hh
  tests/src/testfeelement.hh
  tests/src/testklshell.cpp
  tests/src/testnonlinearelasticity.hh
Labels: bug

#231 update LICENSE.md
  LICENSE.md
Labels: documentation

#223 Refactor getDisplacementFunction
  CHANGELOG.md
  docs/website/01_framework/finiteElements.md
  ikarus/finiteelements/CMakeLists.txt
  ikarus/finiteelements/fehelper.hh
  ikarus/finiteelements/mechanics/enhancedassumedstrains.hh
  ikarus/finiteelements/mechanics/kirchhoffloveshell.hh
  ikarus/finiteelements/mechanics/linearelastic.hh
  ikarus/finiteelements/mechanics/nonlinearelastic.hh
  ikarus/python/finiteelements/registerelement.hh
  tests/src/testklshell.cpp
Labels: refactor

#221 Refactor load functionalities
  CHANGELOG.md
  ikarus/finiteelements/febases/autodifffe.hh
  ikarus/finiteelements/fehelper.hh
  ikarus/finiteelements/mechanics/CMakeLists.txt
  ikarus/finiteelements/mechanics/enhancedassumedstrains.hh
  ikarus/finiteelements/mechanics/kirchhoffloveshell.hh
  ikarus/finiteelements/mechanics/linearelastic.hh
  ikarus/finiteelements/mechanics/loads.hh
  ikarus/finiteelements/mechanics/loads/CMakeLists.txt
  ikarus/finiteelements/mechanics/loads/traction.hh
  ikarus/finiteelements/mechanics/loads/volume.hh
  ikarus/finiteelements/mechanics/nonlinearelastic.hh
  ikarus/finiteelements/physicshelper.hh
Labels: refactor

#238 add tensorProduct quadrature rule and [0,1] to [-1,1] transformation
  ikarus/utils/CMakeLists.txt
  ikarus/utils/tensorproductquadrule.hh
  tests/src/testshellthicknessquadrule.cpp
Labels: feature

#249 merge FETraits and TraitsFromFE to avoid code duplication
  docs/website/02_examples/incompressibleRubberBlock.md
  docs/website/02_examples/kirchhoffPlate.md
  docs/website/02_examples/vonMisesTruss.md
  ikarus/finiteelements/febases/autodifffe.hh
  ikarus/finiteelements/febases/powerbasisfe.hh
  ikarus/finiteelements/febases/scalarfe.hh
  ikarus/finiteelements/fetraits.hh
  ikarus/finiteelements/mechanics/kirchhoffloveshell.hh
  ikarus/finiteelements/mechanics/linearelastic.hh
  ikarus/finiteelements/mechanics/nonlinearelastic.hh
  ikarus/finiteelements/physicshelper.hh
  tests/src/checkfebyautodiff.hh
Labels: enhancement, refactor

#247 refactor enhancedassumedstrains.hh
  CHANGELOG.md
  docs/website/01_framework/finiteElements.md
  ikarus/finiteelements/mechanics/CMakeLists.txt
  ikarus/finiteelements/mechanics/eas/CMakeLists.txt
  ikarus/finiteelements/mechanics/eas/eas2d.hh
  ikarus/finiteelements/mechanics/eas/eas3d.hh
  ikarus/finiteelements/mechanics/easvariants.hh
  ikarus/finiteelements/mechanics/enhancedassumedstrains.hh
  ikarus/utils/tensorutils.hh
Labels: enhancement, refactor

#245 Refactor ResultTypeMap
  CHANGELOG.md
  ikarus/finiteelements/ferequirements.hh
  ikarus/finiteelements/fetraits.hh
  ikarus/finiteelements/mechanics/enhancedassumedstrains.hh
  ikarus/finiteelements/mechanics/kirchhoffloveshell.hh
  ikarus/finiteelements/mechanics/linearelastic.hh
  ikarus/finiteelements/mechanics/nonlinearelastic.hh
  ikarus/io/resultevaluators.hh
  ikarus/io/resultfunction.hh
  ikarus/python/finiteelements/nonlinearelastic.hh
  ikarus/python/finiteelements/registerelement.hh
  ikarus/python/test/linearelastictest.py
  ikarus/python/test/nonlinearelastictest.py
  python/ikarus/_ikarus.cc
  tests/src/resultcollection.hh
  tests/src/testcommon.hh
  tests/src/testenhancedassumedstrains.cpp
  tests/src/testfeelement.hh
  tests/src/testlinearelasticity.cpp
  tests/src/testnonlinearelasticity.hh
Labels: refactor
