Repository ikarus-project/ikarus, pull requests merged in 2024-02, with the labels that each got.

#251 Revisit ResultEvaluators
  CHANGELOG.md
  ikarus/io/resultevaluators.hh
  ikarus/io/resultfunction.hh
  ikarus/utils/tensorutils.hh
  tests/src/resultcollection.hh
  tests/src/testcommon.hh
  tests/src/testenhancedassumedstrains.cpp
  tests/src/testfeelement.hh
  tests/src/testlinearelasticity.cpp
  tests/src/testnonlinearelasticity.hh
  tests/src/testnonlinearelasticityneohooke.cpp
  tests/src/testnonlinearelasticitysvk.cpp
Labels: enhancement

#256 refactor febase to handle any type of basis
  CHANGELOG.md
  docs/website/01_framework/finiteElements.md
  docs/website/02_examples/incompressibleRubberBlock.md
  docs/website/02_examples/kirchhoffPlate.md
  docs/website/02_examples/vonMisesTruss.md
  ikarus/assembler/simpleassemblers.hh
  ikarus/assembler/simpleassemblers.inl
  ikarus/finiteelements/CMakeLists.txt
  ikarus/finiteelements/autodiff/CMakeLists.txt
  ikarus/finiteelements/autodiff/autodifffe.hh
  ikarus/finiteelements/febase.hh
  ikarus/finiteelements/febases/powerbasisfe.hh
  ikarus/finiteelements/febases/scalarfe.hh
  ikarus/finiteelements/fehelper.hh
  ikarus/finiteelements/fetraits.hh
  ikarus/finiteelements/mechanics/kirchhoffloveshell.hh
  ikarus/finiteelements/mechanics/linearelastic.hh
  ikarus/finiteelements/mechanics/nonlinearelastic.hh
  ikarus/python/basis/basis.hh
  ikarus/python/finiteelements/kirchhoffloveshell.hh
  ikarus/python/finiteelements/nonlinearelastic.hh
  ikarus/python/finiteelements/registerelement.hh
  ikarus/python/test/kltest.py
  ikarus/utils/CMakeLists.txt
  ikarus/utils/basis.hh
  ikarus/utils/concepts.hh
  ikarus/utils/traversal.hh
  python/ikarus/basis.py
  python/ikarus/finite_elements/__init__.py
  tests/src/checkfebyautodiff.hh
  tests/src/testcommon.hh
  tests/src/testfebases.cpp
Labels: enhancement, feature, refactor

#259 move autodiffhelper from utils to autodiff folder
  CHANGELOG.md
  ikarus/finiteelements/autodiff/CMakeLists.txt
  ikarus/finiteelements/autodiff/autodiffhelper.hh
  ikarus/utils/CMakeLists.txt
  tests/src/testautodiffhelper.cpp
Labels: refactor
