Repository ikarus-project/ikarus, pull requests merged in 2025-05, with the labels that each got.

#374 Fix Release Workflow
  .github/workflows/createRelease.yml
Labels: workflow

#372 Add push-forward and pull-back of stress measures
  CHANGELOG.md
  ikarus/finiteelements/mechanics/materials/CMakeLists.txt
  ikarus/finiteelements/mechanics/materials/materialhelpers.hh
  ikarus/finiteelements/mechanics/materials/strainconversions.hh
  ikarus/finiteelements/mechanics/materials/stressconversions.hh
  ikarus/finiteelements/mechanics/materials/tags.hh
  tests/src/CMakeLists.txt
  tests/src/testconversions.cpp
Labels: enhancement

#381 Synchronize notion of step count between LoadControl and PathFollowing
  ikarus/controlroutines/loadcontrol.hh
  ikarus/controlroutines/loadcontrol.inl
  ikarus/controlroutines/pathfollowing.hh
  ikarus/controlroutines/pathfollowing.inl
  ikarus/controlroutines/pathfollowingfunctions.hh
  tests/src/testadaptivestepsizing.cpp
  tests/src/testpathfollowing.cpp
Labels: bug, enhancement
